//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowe_IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class partsdb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partsdb()
        {
            this.productsparts = new HashSet<productspart>();
        }
    
        public int partid { get; set; }
        public Nullable<int> createdby { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public int instock { get; set; }
        public int min { get; set; }
        public int max { get; set; }
        public string type { get; set; }
        public string details { get; set; }
        public System.DateTime lastmodified { get; set; }
    
        public virtual usertable usertable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productspart> productsparts { get; set; }
    }
}
