//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowe_IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class productspart
    {
        public int productpartid { get; set; }
        public int productid { get; set; }
        public int partid { get; set; }
    
        public virtual partsdb partsdb { get; set; }
        public virtual productsdb productsdb { get; set; }
    }
}
